import { Alert, Anchor, Badge, Box, Button, Checkbox, Group, Loader, Select, Stack, Table, Text, TextInput, Title } from "@mantine/core";
import { Save } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { fetchEvent, updateEventOutcomes } from "../../features/events/api/events";
import type { EventDetail, EventPlayerAward, EventTeamResult, PlayerAwardType } from "../../features/events/types";
import "../../features/events/components/EventForm.css";

const AWARDS: Array<{ type: PlayerAwardType; label: string; limit: number }> = [
  { type: "EVENT_MVP", label: "Event MVP", limit: 1 },
  { type: "ALL_EVENT_FIRST_TEAM", label: "All-event First Team", limit: 5 },
  { type: "ALL_EVENT_SECOND_TEAM", label: "All-event Second Team", limit: 5 }
];

export function EventOutcomesPage({ eventId }: { eventId: string }) {
  const [event, setEvent] = useState<EventDetail | null>(null); const [results, setResults] = useState<Array<Partial<EventTeamResult> & { teamId: number; teamName: string }>>([]);
  const [awards, setAwards] = useState<EventPlayerAward[]>([]); const [filterTeam, setFilterTeam] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { const controller = new AbortController(); fetchEvent(eventId, controller.signal).then((data) => { setEvent(data); setResults(data.participants.map((participant) => ({ teamId: participant.teamId, teamName: participant.teamName, ...data.teamResults.find((result) => result.teamId === participant.teamId) }))); setAwards(data.playerAwards); }).catch((reason) => { if (!(reason instanceof DOMException && reason.name === "AbortError")) setError(reason instanceof Error ? reason.message : "Unable to load outcomes."); }).finally(() => setLoading(false)); return () => controller.abort(); }, [eventId]);
  const readOnly = Boolean(event?.archivedAt) || event?.status === "COMPLETED";
  const candidates = useMemo(() => event?.awardCandidatePlayers.filter((player) => !filterTeam || String(player.teamId) === filterTeam) ?? [], [event, filterTeam]);
  function selected(type: PlayerAwardType, playerId: number) { return awards.some((award) => award.awardType === type && award.playerId === playerId); }
  function toggle(type: PlayerAwardType, playerId: number) { if (!event) return; const existing = awards.find((award) => award.awardType === type && award.playerId === playerId); if (existing) { setAwards(awards.filter((award) => award !== existing)); return; } const config = AWARDS.find((item) => item.type === type)!; if (awards.filter((award) => award.awardType === type).length >= config.limit) return; const player = event.awardCandidatePlayers.find((item) => item.playerId === playerId)!; setAwards([...awards, { id: -Date.now(), awardType: type, playerId, playerSlug: player.playerSlug, playerName: player.playerName, playerIsActive: true, teamId: player.teamId, teamSlug: player.teamSlug, teamName: player.teamName, notes: null }]); }
  async function save() { if (!event) return; setSaving(true); setError(""); try { const updated = await updateEventOutcomes(event.slug, { teamResults: results.filter((result) => result.resultTagId).map((result) => ({ teamId: result.teamId, resultTagId: result.resultTagId!, notes: result.notes ?? null })), playerAwards: awards.map((award) => ({ awardType: award.awardType, playerId: award.playerId, teamId: award.teamId, notes: award.notes })) }); setEvent(updated); setAwards(updated.playerAwards); setResults(updated.participants.map((participant) => ({ teamId: participant.teamId, teamName: participant.teamName, ...updated.teamResults.find((result) => result.teamId === participant.teamId) }))); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save outcomes."); } finally { setSaving(false); } }
  if (loading) return <Loader size="sm"/>; if (!event) return <Alert color="red">{error || "Event not found."}</Alert>;
  return <Stack gap="lg"><Group align="center" justify="space-between"><Box><Title order={1}>{event.name}: Results & Awards</Title><Text c="dimmed">{event.status}</Text></Box><Group gap="sm">{!readOnly ? <Button className="app-action-button app-action-button--primary" loading={saving} leftSection={<Save size={16}/>} onClick={save}>Save Outcomes</Button> : null}<Anchor className="event-outcomes-back-link" href={`/events/${event.slug}`}>← Back to Event</Anchor></Group></Group>
    {readOnly ? <Alert color="yellow" title="Read-only outcomes">{event.archivedAt ? "Archived events cannot be modified." : "Reopen this event from Edit Event to correct outcomes."}</Alert> : null}{error ? <Alert color="red">{error}</Alert> : null}
    <Box className="event-form-panel"><Group justify="space-between"><Title order={2}>Team Results</Title><Anchor href={`/events/${event.slug}/edit`}>Edit Result Tags</Anchor></Group>{event.participants.length === 0 ? <Alert mt="md">Add participating teams before recording results.</Alert> : event.resultTags.length === 0 ? <Alert mt="md">Create at least one ResultTag before recording results.</Alert> : <Table mt="md"><Table.Thead><Table.Tr><Table.Th>Team</Table.Th><Table.Th>Result</Table.Th><Table.Th>Notes</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{results.map((result,index) => <Table.Tr key={result.teamId}><Table.Td>{result.teamName}</Table.Td><Table.Td><Select disabled={readOnly} clearable data={event.resultTags.map((tag) => ({ value:String(tag.id), label:`${tag.label} (${tag.rankingPoints})` }))} value={result.resultTagId ? String(result.resultTagId) : null} onChange={(value) => setResults(results.map((item,i) => i === index ? {...item,resultTagId:value ? Number(value) : undefined}:item))}/></Table.Td><Table.Td><TextInput disabled={readOnly} value={result.notes ?? ""} onChange={(e) => setResults(results.map((item,i) => i === index ? {...item,notes:e.currentTarget.value}:item))}/></Table.Td></Table.Tr>)}</Table.Tbody></Table>}</Box>
    <Box className="event-form-panel"><Group justify="space-between"><Title order={2}>Player Awards</Title><Select clearable placeholder="All teams" data={event.participants.map((team) => ({value:String(team.teamId),label:team.teamName}))} value={filterTeam} onChange={setFilterTeam}/></Group>{event.awardCandidatePlayers.length === 0 && awards.length === 0 ? <Alert mt="md">No active award candidates.</Alert> : <Stack mt="md">{AWARDS.map((config) => <Box key={config.type}><Group><Text fw={600}>{config.label}</Text><Badge>{awards.filter((award) => award.awardType === config.type).length}/{config.limit}</Badge></Group><Group mt="xs">{candidates.map((player) => { const otherTeam = config.type === "ALL_EVENT_FIRST_TEAM" ? "ALL_EVENT_SECOND_TEAM" : config.type === "ALL_EVENT_SECOND_TEAM" ? "ALL_EVENT_FIRST_TEAM" : null; return <Checkbox key={player.playerId} checked={selected(config.type,player.playerId)} disabled={readOnly || Boolean(otherTeam && selected(otherTeam,player.playerId))} label={`${player.playerName} · ${player.teamName}`} onChange={() => toggle(config.type,player.playerId)}/>; })}{awards.filter((award) => award.awardType === config.type && !award.playerIsActive).map((award) => <Checkbox key={`inactive-${award.id}`} checked disabled={readOnly} label={`${award.playerName} · ${award.teamName} (Inactive)`} onChange={() => setAwards(awards.filter((item) => item.id !== award.id))}/>)}</Group></Box>)}</Stack>}</Box>
  </Stack>;
}
