import { Box, Checkbox, NumberInput, Table, Text, Title } from "@mantine/core";
import type { OtherStatPayload } from "../../../features/matches";
import type { MatchFormTeam, OtherStatDraft, PlayerEntry, PlayerStatInput } from "../types";

const playerColumns: Array<{ key: keyof PlayerStatInput; label: string; max: number; step: number }> = [
  { key: "points", label: "PTS", max: 10000, step: 1 }, { key: "rebounds", label: "REB", max: 10000, step: 1 }, { key: "assists", label: "AST", max: 10000, step: 1 }, { key: "fieldGoalsMade", label: "FGM", max: 10000, step: 1 }, { key: "fieldGoalsAttempted", label: "FGA", max: 10000, step: 1 }, { key: "threePointersMade", label: "3PM", max: 10000, step: 1 }, { key: "threePointersAttempted", label: "3PA", max: 10000, step: 1 }, { key: "minutes", label: "MIN", max: 10000, step: 1 }, { key: "rating", label: "RTG", max: 10, step: 0.1 }
];
const otherKeys: Array<keyof OtherStatPayload> = ["points","rebounds","assists","fieldGoalsMade","fieldGoalsAttempted","threePointersMade","threePointersAttempted"];
// Empty input -> null so a cleared cell stays blank instead of snapping to 0.
const toStatValue = (value: string | number): number | null => { if (value === "") return null; const parsed = typeof value === "number" ? value : Number(value); return Number.isNaN(parsed) ? null : parsed; };
export function MatchStatsInputTable({ team, entries, otherStats, onToggle, onPlayerStatChange, onOtherStatChange }: { team: MatchFormTeam; entries: Record<number, PlayerEntry>; otherStats: OtherStatDraft; onToggle: (id: number, checked: boolean) => void; onPlayerStatChange: (id: number, key: keyof PlayerStatInput, value: number | null) => void; onOtherStatChange: (key: keyof OtherStatPayload, value: number | null) => void }) {
  const score = Object.values(entries).filter((entry) => entry.appeared).reduce((sum, entry) => sum + (entry.stats.points ?? 0), otherStats.points ?? 0);
  return <Box className="match-form-section match-stats-section app-surface app-surface--editor"><Title className="match-stats-title" order={2}><span aria-hidden="true" className="match-stats-title-bar" style={{ backgroundColor: team.color ?? undefined }} />{team.name}{team.archivedAt ? " (Archived)" : ""}<span className="match-stats-score">Score {score}</span></Title><Box className="match-stats-table-scroll app-table-wrap"><Table className="match-stats-input-table app-data-table"><Table.Thead><Table.Tr><Table.Th>Played</Table.Th><Table.Th>POS</Table.Th><Table.Th>Player</Table.Th>{playerColumns.map((column) => <Table.Th key={column.key}>{column.label}</Table.Th>)}</Table.Tr></Table.Thead><Table.Tbody>
    {team.players.map((player) => { const entry = entries[player.id]!; return <Table.Tr key={player.id}><Table.Td><Checkbox aria-label={`${player.name} played`} checked={entry.appeared} onChange={(event) => onToggle(player.id, event.currentTarget.checked)} /></Table.Td><Table.Td>{player.position}</Table.Td><Table.Td><Text className="match-stats-player-name">{player.name}{!player.isActive ? " (Inactive)" : ""}</Text></Table.Td>{playerColumns.map((column) => <Table.Td key={column.key}><NumberInput allowDecimal={column.step < 1} classNames={{ input: "match-stats-input" }} decimalScale={column.step < 1 ? 1 : 0} disabled={!entry.appeared} max={column.max} min={0} onChange={(value) => onPlayerStatChange(player.id, column.key, toStatValue(value))} step={column.step} value={entry.stats[column.key] ?? ""} /></Table.Td>)}</Table.Tr>; })}
    <Table.Tr className="match-stats-other-row app-data-row--operational"><Table.Td>—</Table.Td><Table.Td>—</Table.Td><Table.Td>Other</Table.Td>{playerColumns.map((column) => <Table.Td key={column.key}>{otherKeys.includes(column.key as keyof OtherStatPayload) ? <NumberInput classNames={{ input: "match-stats-input" }} max={10000} min={0} onChange={(value) => onOtherStatChange(column.key as keyof OtherStatPayload, toStatValue(value))} step={1} value={otherStats[column.key as keyof OtherStatDraft] ?? ""} /> : "—"}</Table.Td>)}</Table.Tr>
  </Table.Tbody></Table></Box></Box>;
}
