import { Box, Checkbox, NumberInput, Table, Text, Title } from "@mantine/core";
import type { OtherStatPayload } from "../../../features/matches";
import type { MatchFormTeam, PlayerEntry, PlayerStatInput } from "../types";

const playerColumns: Array<{ key: keyof PlayerStatInput; label: string; max: number; step: number }> = [
  { key: "points", label: "PTS", max: 10000, step: 1 }, { key: "rebounds", label: "REB", max: 10000, step: 1 }, { key: "assists", label: "AST", max: 10000, step: 1 }, { key: "fieldGoalsMade", label: "FGM", max: 10000, step: 1 }, { key: "fieldGoalsAttempted", label: "FGA", max: 10000, step: 1 }, { key: "threePointersMade", label: "3PM", max: 10000, step: 1 }, { key: "threePointersAttempted", label: "3PA", max: 10000, step: 1 }, { key: "minutes", label: "MIN", max: 10000, step: 1 }, { key: "rating", label: "RTG", max: 10, step: 0.1 }
];
const otherKeys: Array<keyof OtherStatPayload> = ["points","rebounds","assists","fieldGoalsMade","fieldGoalsAttempted","threePointersMade","threePointersAttempted"];
const number = (value: string | number) => typeof value === "number" ? value : Number(value) || 0;
export function MatchStatsInputTable({ team, entries, otherStats, onToggle, onPlayerStatChange, onOtherStatChange }: { team: MatchFormTeam; entries: Record<number, PlayerEntry>; otherStats: OtherStatPayload; onToggle: (id: number, checked: boolean) => void; onPlayerStatChange: (id: number, key: keyof PlayerStatInput, value: number) => void; onOtherStatChange: (key: keyof OtherStatPayload, value: number) => void }) {
  const score = Object.values(entries).filter((entry) => entry.appeared).reduce((sum, entry) => sum + entry.stats.points, otherStats.points);
  return <Box className="match-form-section match-stats-section app-panel"><Title className="match-stats-title" order={2}><span aria-hidden="true" className="match-stats-title-bar" style={{ backgroundColor: team.color ?? undefined }} />{team.name}{team.archivedAt ? " (Archived)" : ""}<span className="match-stats-score">Score {score}</span></Title><Box className="match-stats-table-scroll"><Table className="match-stats-input-table"><Table.Thead><Table.Tr><Table.Th>Played</Table.Th><Table.Th>POS</Table.Th><Table.Th>Player</Table.Th>{playerColumns.map((column) => <Table.Th key={column.key}>{column.label}</Table.Th>)}</Table.Tr></Table.Thead><Table.Tbody>
    {team.players.map((player) => { const entry = entries[player.id]!; return <Table.Tr key={player.id}><Table.Td><Checkbox aria-label={`${player.name} played`} checked={entry.appeared} onChange={(event) => onToggle(player.id, event.currentTarget.checked)} /></Table.Td><Table.Td>{player.position}</Table.Td><Table.Td><Text className="match-stats-player-name">{player.name}{!player.isActive ? " (Inactive)" : ""}</Text></Table.Td>{playerColumns.map((column) => <Table.Td key={column.key}><NumberInput allowDecimal={column.step < 1} classNames={{ input: "match-stats-input" }} decimalScale={column.step < 1 ? 1 : 0} disabled={!entry.appeared} max={column.max} min={0} onChange={(value) => onPlayerStatChange(player.id, column.key, number(value))} step={column.step} value={entry.appeared ? entry.stats[column.key] : column.key === "rating" ? "" : 0} /></Table.Td>)}</Table.Tr>; })}
    <Table.Tr className="match-stats-other-row"><Table.Td>—</Table.Td><Table.Td>—</Table.Td><Table.Td>Other</Table.Td>{playerColumns.map((column) => <Table.Td key={column.key}>{otherKeys.includes(column.key as keyof OtherStatPayload) ? <NumberInput classNames={{ input: "match-stats-input" }} max={10000} min={0} onChange={(value) => onOtherStatChange(column.key as keyof OtherStatPayload, number(value))} step={1} value={otherStats[column.key as keyof OtherStatPayload]} /> : "—"}</Table.Td>)}</Table.Tr>
  </Table.Tbody></Table></Box></Box>;
}
